<a href="https://colab.research.google.com/github/nehat005/Python-Numpy/blob/master/ArraysvsLists.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [55]:

L=[1,2,3]
A=np.array([1,2,3,4])


In [56]:
#Adding elements to Lists:
#1st method :
Lap2=L.append(4) 
print(Lap2)

#2nd method
L2=L+[5,6] 
print(L, L2)

#3rd method
print(2*L)  #cant do L*L for concatenation

None
[1, 2, 3, 4] [1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 1, 2, 3, 4]


In [40]:
#Adding elements to Arrays:

#1st method: Convert to List, add elements to the list and convert back to numpy array
AL=A.tolist()
AL=AL+[5,6]
A3=np.array(AL)
print(A3)
print(type(A3))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [51]:
#Broadcasting in NUMPY: 1-element array is added to n-elements array :

#In 1-dim array such as: 
#A=np.array([1,2,3,4])
A2=A+np.array([4])
print("A2=",A2)
print("\n")

#In n-dim array:
A4=np.array([[1,2,3],[4,5,6]])
A4=A4 + np.array([1,2,3])
print("A4=",A4)

A2= [5 6 7 8]


A4= [[2 4 6]
 [5 7 9]]


In [58]:
#Multiplication in Np:

A=2*A
print(A)

#Addition/Multiplication/squares/sqrt/division in Lists:
L2=[]
for e in L:
  L2.append(e*2)

L2

#Using List comprehension:
L_2=[e+3 for e in L]
print(L_2)

[ 4  8 12 16]
[4, 5, 6, 7]
